<div class="container">
	<h2 class="pb-lg-5">Přihlášení do aplikace</h2>

	<div class="row">
		<form action="" class="col" method="post">
			
			<div class="d-sm-flex">
				<div class="form-group col-md-6">
					<label for="prezdivka">Přihlašovací jméno - přezdívka</label>
					<input type="text" class="form-control" id="prezdivka" name="prezdivka" placeholder="josefnovy" />
				</div>
				<div class="form-group col-md-6">
					<label for="heslo">Heslo</label>
					<input type="password" class="form-control" id="heslo" name="heslo" />
				</div>
			</div>

			<div class="d-sm-flex col-md-12 justify-content-center">
				<input type="submit" class="btn btn-primary px-5 mt-lg-5" value="Přihlásit">
			</div>
		</form>
	</div>

	<div class="mt-lg-5">
		<p>
			Jste-li zde poprvé, připravte si prosím údaje z pojistné smlouvy a <a href="registrace">zaregistrujte se</a>.
		</p>
	</div>
</div>