<!DOCTYPE html>
<html lang="cs-cz">

<head>
	<base href="/localhost" />
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
	<title><?= $titulek ?></title>
	<meta name="description" content="<?= $popis ?>" />
	<meta name="keywords" content="<?= $klicova_slova ?>" />
	<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top justify-content-between">
			<div class="d-inline-flex">
				<!-- Brand/logo -->
				<a class="navbar-brand">PojištěníApp</a>
				<!-- Links -->
				<ul class="navbar-nav ml-5">
					<li class="nav-item">
						<a class="nav-link" <?php if (!$prezdivka) {echo "href=prihlaseni";} else {echo "href='pojistenci'";} ?>><?php if (!$admin) {echo 'Pojištění'; } else {echo 'Pojištěnci';} ?></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" <?php if (!$prezdivka) {echo "href=prihlaseni";} else {echo "href='udalosti'";} ?>>Události</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" <?php if (!$prezdivka) {echo "href=prihlaseni";} else {echo "href='hlaseni'";} ?>>Hlášení</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="o-aplikaci">O&nbsp;aplikaci</a>
					</li>
				</ul>
			</div>
			<?php if ($prezdivka) : ?>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link active"><?= $prezdivka ?></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="prihlaseni/odhlasit">Odhlásit</a>
					</li>
				</ul>
			<?php else : ?>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="prihlaseni">Přihlásit</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="registrace">Registrovat</a>
					</li>
				</ul>
			<?php endif ?>
		</nav>
	</header>
	<article>
		<div class="container-fluid">
		<?php foreach ($zpravy as $zprava) {
			
			foreach ($zprava as $typ => $text) {
				echo '<div class="' . $typ . '">' . $text . '</div>';
			}
		}
		?>
		</div>
		<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony 
		?>
	</article>

</body>

</html>